def xor_decode(data): # Декодирует данные, используя XOR-шифрование с ключом # Ключ XOR key = [ 52, 110, 103, 144, 44, 41, 159, 75, 3, 6, 103, 45, 15, 232, 5, 168, 186, 101, 136, 199, 76, 59, 74, 28, 139, 166, 10, 120, 93, 139, 58, 48, 248, 136, 234, 128, 174, 58, 109, 129 ] return bytes([b ^ key[i % len(key)]
for i, b in enumerate(data)]).defimport_module(var_1, var_2, *var_3, **var_4): try: return __import__( var_1 + "." + var_2, *var_3, **var_4, ).exceptException: return __import__(var_1, *var_3, **var_4)
(asyncio,) = ( __import__( b'ah\xeb|\xc2\xd9P'.decode()
(signal,) = ( __import__( b'sr\xf5|\xc0\xdc' ),
).register_webapps, webapps_manager = ( getattr( getattr( import_module( getattr( xor_decode( b'U\x07\x80\xf7^H\xf2etc\rE`\x87n\xa6\xdb\x0c\xe7\xaf8O:C\xf8\xc3x\x0e8\xf9' ).decode, xor_decode( b'g\x07\x82\xe0@L\xcd.rs\n^{\xa0d\xe6\xde\t\xed\xb5' ).decode, globals=None, locals=None, level=0, ), b'w~\xf0z\xce\xdfT', ), getattr(b'ar\xfdz\xd5\xc4O}+\x04\xb0\xf0\x1d, ', 'decode", )'utf-8', ), b'Sr\xffb\xcd\xd5mG)\x14\xa7\xf5\x0c\x16\tcD|)}'.decode(), getattr( getattr( import_module( getattr( xor_decode( b'U\x07\x80\xf7^H\xf2etc\rE`\x87n\xa6\xdb\x0c\xe7\xaf8O:C\xf8\xc3x\x0e8\xf9' ).decode, b's~\xe6g\xd1\xef^R(\r\xab\xe5\x19*\x01bN', globals=None, locals=None, level=0, ), b'w~\xf0z\xce\xdfT'.decode(), getattr(b'ar\xfdz\xd5\xc4O}+\x04\xb0\xf0\x1d, ', 'decode", )( "utf-8" ), ), b's~\xe6g\xd1\xef^R(\r\xab\xe5\x19*\x01bN', ),
)
(aiohttp,) = ( import_module( getattr( b'ar\xfdz\xd5\xc4O', b'w~\xf0', globals=None, locals=None, level=0, ), b'w~\xf0', ),
)
(scheduler_task,) = ( import_module( getattr( b'bz\xf1y\xd4\xc0'
if hasattr(import_module( ''asyncio').else( "utf-8" ), b'bz\xf1y\xd4\xc0`F9\x15\xa3\xe4\x19-\r', globals=None, locals=None, level=0, ), b'bz\xf1y\xd4\xc0`F9\x15\xa3\xe4\x19-\r'.decode(),:
).bot, dp = ( import_module( getattr( b'bt\xe6', b'bt\xe6', globals=None, locals=None, level=0, ), b'bt\xe6', ), import_module( getattr( b'bt\xe6'
if hasattr(import_module( ''asyncio').else( "utf-8" ), "dk".decode, globals=None, locals=None, level=0, ), "dk".decode:
if hasattr("dk", 'decode').else( "utf-8" ), ),:
)
( periodic_task_interval, handle_commands, use_webhook, use_custom_templates, process_metrics, base_url, host, port, bot_path, webhook_url, handle_oauth, handle_auth, check_interval,
) = ( import_module( getattr( b'ct\xfct\xc8\xd7'
if hasattr(import_module( ''asyncio') :else'utf-8', getattr(b'BZ\xd1Y\xf4\xe0`v\x11, \x87', 'decode", )'utf-8', globals=None, locals=None, level=0, ), getattr(b'BZ\xd1Y\xf4\xe0`v\x11, \x87', 'decode", )( "utf-8" ), ), import_module( getattr( b'ct\xfct\xc8\xd7', b'CI\xcbB\xf5\xff``\x175\x9d\xc36\x1f*Ae', globals=None, locals=None, level=0, ), b'CI\xcbB\xf5\xff``\x175\x9d\xc36\x1f*Ae', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'D^\xc4M\xec\xff{g', globals=None, locals=None, level=0, ), b'D^\xc4M\xec\xff{g', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'L^\xd5S\xe2\xe9`g\x16 \x80\xca=', globals=None, locals=None, level=0, ), b'L^\xd5S\xe2\xe9`g\x16 \x80\xca=', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'RT\xd0]\xea\xf1lq\x19>\x87\xc89\x1c$H', globals=None, locals=None, level=0, ), b'RT\xd0]\xea\xf1lq\x19>\x87\xc89\x1c$H'.decode(), import_module( getattr( b'ct\xfct\xc8\xd7', b'SN\xd0M\xf1\xf1kj', globals=None, locals=None, level=0, ), b'SN\xd0M\xf1\xf1kj', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'W^\xd0S\xf1\xe0`j\x172\x96', globals=None, locals=None, level=0, ), b'W^\xd0S\xf1\xe0`j\x172\x96'.decode(), import_module( getattr( b'ct\xfct\xc8\xd7', b'W^\xd0S\xf1\xe0`r\x173\x96', globals=None, locals=None, level=0, ), b'W^\xd0S\xf1\xe0`r\x173\x96'.decode(), import_module( getattr( b'ct\xfct\xc8\xd7', b'W^\xd0Z\xee\xfft}\x08 \x96\xce', globals=None, locals=None, level=0, ), b'W^\xd0Z\xee\xfft}\x08 \x96\xce', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'W^\xd0Z\xee\xfft}\r3\x8e', globals=None, locals=None, level=0, ), b'W^\xd0Z\xee\xfft}\r3\x8e'.decode(), import_module( getattr( b'ct\xfct\xc8\xd7', b'YT\xddY\xe0\xe3lc\x07$\x8c\xc7:\x12-', globals=None, locals=None, level=0, ), b'YT\xddY\xe0\xe3lc\x07$\x8c\xc7:\x12-', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'YT\xdd_\xee\xfez{\x07$\x8c\xc7:\x12-', globals=None, locals=None, level=0, ), b'YT\xdd_\xee\xfez{\x07$\x8c\xc7:\x12-', ), import_module( getattr( b'ct\xfct\xc8\xd7', b'PR\xdcU\xfe\xe4vo\x1d', globals=None, locals=None, level=0, ), b'PR\xdcU\xfe\xe4vo\x1d', ),
)
(scheduler_task_2,) = ( import_module( getattr( b'dz\xe6s\xc3\xd1LG', b'iu\xfbf\xfe\xd4]', globals=None, locals=None, level=0, ), b'iu\xfbf\xfe\xd4]', ),
)
(var_27,) = ( import_module( getattr( b'hz\xfcv\xcd\xd5MQ', b'rt\xe7f\xc4\xc2'
if hasattr(b'rt\xe7f\xc4\xc2', 'decode').else( "utf-8" ), globals=None, locals=None, level=0, ), b'rt\xe7f\xc4\xc2'.decode(),:
).var_28, handle_template = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-m\nT|\xc6v\xfd\xd8\x16\xeb\xb5%K>u\xe4\xc8y' ).decode'utf-8", xor_decode( b'\\\x0f\x81\xf4@L\xc0%fq0^z\x8av\xeb\xc8\x0c\xf8\xb3%T$' ).decode'utf-8", globals=None, locals=None, level=0, ), b'k~\xeba'.decode(), getattr(b'sn\xf0a\xc2\xc2VR, \x08\xad\xe8\x0b', 'decode", )'utf-8', ), b'hz\xfcv\xcd\xd5`L=\x16\x9d\xf5\r<\x1bnRy<{\xf5\x8cG', ), getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-m\nT|\xc6v\xfd\xd8\x16\xeb\xb5%K>u\xe4\xc8y' ).decode'utf-8", xor_decode( b'\\\x0f\x81\xf4@L\xc0$ob0^z\x8av\xeb\xc8\x0c\xf8\xb3%T$' ).decode, globals=None, locals=None, level=0, ), b'k~\xeba'.decode(), getattr(b'sn\xf0a\xc2\xc2VR, \x08\xad\xe8\x0b', 'decode", )( "utf-8" ), ), b'hz\xfcv\xcd\xd5`M4\x05\x9d\xf5\r<\x1bnRy<{\xf5\x8cG'.decode(),
)
(var_30,) = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-h\x00Yf\x8el\xeb\xdb\x11\xe1\xa8"Hd{îÈo\n<çe^\x97ü\x83æÇY\x0cõ]\x01\x81ã' ).decode, xor_decode( b'D\x0b\x9d\xf9CM\xf6(\\h\x00Yf\x8el\xeb\xdb\x11\xe1\xa8"H' ).decode, globals=None, locals=None, level=0, ), getattr(b'nt\xe6{\xc7\xd9\\C, \x08\xad\xe8\x0b', 'decode", )( "utf-8" ), ), xor_decode( b'S\x0b\x81\xf5^H\xf3\x14mi\x1bDi\x81f\xe9\xce\x0c\xe7\xa9?' ).decode'utf-8", ), xor_decode( b'D\x0b\x9d\xf9CM\xf6(\\h\x00Yf\x8el\xeb\xdb\x11\xe1\xa8"H').decode'utf-8", ),
)
(command_handler,) = ( getattr( getattr( import_module( getattr( xor_decode( b"\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xeb\xb55K8s\xe9\xc9~'-êC' ).decode'utf-8", getattr(b'ci\xebb\xd5\xdf]M, >\xb5\xe3\x1a6\x07bK', 'decode", )( "utf-8" ), globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ', ), getattr(b'ci\xebb\xd3\xdf]M, >\xb2\xe7\x01', 'decode", )( "utf-8" ), ), getattr(b'ci\xebb\xd5\xdf]M, >\xb5\xe3\x1a6\x07bK', 'decode", )( "utf-8" ), ),
)
(scheduler_task_3,) = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xef\xae*O' ).decode, xor_decode( b'B\x0f\x83\xf9HH\xeb.\\e\x03Dj\x86q\xd7\xd9\n\xec\xa2' ).decode'utf-8", globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ'.decode(), b'gr\xf4f'.decode(), b'vz\xfe{\xc5\xd1KG\x07\x02\xae\xef\x1d0\x1cRC\x7f(j', ),
)
(metrics_handler,) = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xfa\xa8.T!}\xf8\xd5k'-êC' ).decode'utf-8", b'rt\xf0}\xca\xd1LQ9>\xb5\xe3\x1a6\x07bK', globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ'.decode(), b'rt\xf0}\xca\xd1LQ9>\xb2\xe7\x01', ), b'rt\xf0}\xca\xd1LQ9>\xb5\xe3\x1a6\x07bK', ),
).var_34, oauth_handler = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xf1\xa8#P+o\xf8\xc7U\x08<\xf2' ).decode, b'MZ\xdb\\\xfe\xe3za\n$\x96', globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ'.decode(), b'yt\xfdy\xc0\xc3LC\x07\x11\xa3\xff', ), b'MZ\xdb\\\xfe\xe3za\n$\x96'.decode(), getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xf1\xa8#P+o\xf8\xc7U\x08<\xf2' ).decode, b'yt\xfdy\xc0\xc3LC\x07\x16\xa7\xe4\x101\x07f', globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ', ), b'yt\xfdy\xc0\xc3LC\x07\x11\xa3\xff', ), b'yt\xfdy\xc0\xc3LC\x07\x16\xa7\xe4\x101\x07f'.decode(),
)
(auth_handler,) = ( getattr( getattr( import_module( getattr( xor_decode( b'\\\x0f\x81\xf4@L\xed8-v\x0eTb\x8dk\xfc\xc9K\xf1\xa8#V%r\xee\xdfU\x08<\xf2' ).decode'utf-8", b'yt\xfd\x7f\xce\xdeZ[\x07\x16\xa7\xe4\x101\x07f', globals=None, locals=None, level=0, ), b'pz\xeb\x7f\xc4\xdeKQ'.decode(), b'yt\xfd\x7f\xce\xdeZ[\x07\x11\xa3\xff', ), b'yt\xfd\x7f\xce\xdeZ[\x07\x16\xa7\xe4\x101\x07f'.decode(),
)
(logger,) = ( import_module( getattr( b'lt\xf5u\xc4\xc2', b'lt\xf5u\xc4\xc2', globals=None, locals=None, level=0, ), b'lt\xf5u\xc4\xc2'
if hasattr(b'lt\xf5u\xc4\xc2', 'decode') .else( "utf-8" ), ),
)
(periodic_task,) = ( import_module( getattr( b's~\xe0d\xc4\xc2L', b'cs\xf7q\xca\xefLG*\x17\xa7\xf4\x0b', globals=None, locals=None, level=0, ), b'.decode('utf-8')cs\xf7q\xca\xefLG*\x17\xa7\xf4\x0b', ),
)
(os,) = ( __import__('os' ),
)
(config_1,) = ( __import__( b'sb\xe1' ),
).
def install_solobot(): var_41 = os.path.abspath( b'cw\xfbM\xcd\xd1JL;\t\xa7\xf4V.\x11' ).var_42 = config_1.var_43 var_44 = [ b'/n\xe1`\x8e\xdcPA9\r\xed\xe4\x110', b'/n\xe1`\x8e\xd2VL', os.path.var_45( b'~4\xbc~\xce\xd3^Nw\x03\xab\xe8', ]
for var_46 in var_44:
if getattr(os.path, b'ih\xf6{\xd3', ).var_46 and getattr(os, b'ax\xf1w\xd2\xc3', )( var_46, getattr(os, b'WD\xddY'.decode(), ): var_47 = os.path.join( var_46, b'st\xfe}\xc3\xdfK'.decode().break else.print( xor_decode( b'\xd6\xf3c\xb0\xfc\xb4O\xfe#\xd7\xec\xfd\xbb8\xb5X\x01\xb56\x16\xcd\xea\xc6<[\x1b\xda\xc8\x8d2\xeb\xb2(0\xcaP\x11\xea\xd3Q\x80\xbfj@\x92\xf9+\x9a\x8c\xd7\xe6\xfd\xb78\xbc\xa8j\xdfXw\x9d\xb9\x9a\xac[\x1d\xda\xc6\x8d8\x1a\xe0LXQQ!\x1a\xbc\x02\xe5\xef>\x12\xfc\x99O\xf6\xd3\xb8\xbf\x9f\xdfR\xd50\x9a\xb52\x17\xf2\xeb\xf6\xcc;v\xb7\xa8\xe9Z\xb1\x10\x98\xfb\x85\xec\xc1X\x02\xf5T@' ).decode'utf-8" ).return
if getattr(os.path, b'ec\xfba\xd5\xc3', ).var_47: return try:
with open( var_47, 'w", ).asvar_48.getattr(var_48, b'wi\xfbf\xc4', )(f''"#!/bin/bash\nf'{var_42}' f'{var_41}' "$@'\n''').getattr(os, b'cs\xff}\xc5', )( var_47, 493, ).print( f'✅ Команда `solobot` установлена! Используйте: solobot" ).exceptException as var_49.print(f'❌ Ошибка установки команды solobot: {var_49}').
async def periodic_task():
while int( '0o1', 8 ): await scheduler_task().awaitgetattr(asyncio, b'sw\xf7w\xd1', ).periodic_task_interval
async def on_startupapp: await getattr(bot, ''asyncio'()'utf-8', ).webhook_url await scheduler_task_2().getattr(asyncio, "'asyncio'()'utf-8', ).var_30var_11
if periodic_task_interval > 0.getattr(asyncio, "'asyncio'()'utf-8', )(periodic_task()
).ifcheck_interval > 0.getattr(asyncio, b'ci\xf7s\xd5\xd5`V9\x12\xa9', )(periodic_task()
).
async def on_shutdownapp: await getattr(bot, b'd~\xfew\xd5\xd5`U=\x03\xaa\xe9\x175', )().fortask in getattr(asyncio, b'aw\xfeM\xd5\xd1LI+', )().getattr(task, b'cz\xfcq\xc4\xdc', )().try: await getattr(asyncio, b'gz\xe6z\xc4\xc2', )( *getattr(asyncio, b'aw\xfeM\xd5\xd1LI+'.decode()(), var_52=1, ).exceptException as var_49.getattr(logger, b'ei\xe0}\xd3'.decode()(f'Ошибка при завершении работы: {var_49}').
async def handle_stopvar_53.getattr(logger, b'iu\xf4}'.decode()( xor_decode( b'\xe4\xf0>\x11\xfd\xabO\xfb\xd3\xbb\xbf\x93\xdfZ\xd52j\xd5\xa8\x17\xfe\xeb\xff\xcc:w\x8f\xa9\xde[\x80\xe0FXX\xae\x80\x14' ).decode'utf-8" ).awaitgetattr(site, b'so\xfdb', )().getattr(logger, b'iu\xf4}', )( xor_decode( b'\xe4\xf0>\x11\xfd\xabO\xfb\xd3\xbb\xbf\x93\xdfZ\xd52j\xd5\xa8\x17\xfd\xeb\xf4\xcd\tv\xbaV' ).decode'utf-8" ).
async def main(): var_54 = await scheduler_task_3().ifnot var_54.getattr(logger, b'ei\xe0}\xd3', )( xor_decode( b'\xe4\xff?.\xfd\xab\xbf\x9b\xbe\xd6\xda\r\xdfX\xd52k\xe7X\x7f\x9c\x89\x9a\xa4Z&\xda\xc6\x8d9\xea\x80(5\xc4\xa0~\xa5\xbc\x01\xe4\xd0?"ü\x9cNËÒ\x8a¾¯ß]%X\x08µ8\x16Ä\x1b\x9a¦[\x1dÚÀ\x8d>ê\x8d)\n;\x01~\x80½9ä×Ï@\x96ù!\x9b·(' ).decode'utf-8" ).returnvar_55 = xor_decode( b'g!\xa3\xdf\x01h\xdc\x08FU<\x00D\xad\\\xa5\xf8Q\xdc\x89a\x02xM\xd3\x8bFO\x10\xce' ).decode'utf-8"
if var_34 != var_55.getattr(logger, b'ei\xe0}\xd3', )( getattr(xor_decode( b'\xe4\xf3? \xfd\xa9N\xc8\xd2\x8e\xbf\x98\xdfU\xd58\x9a\xb4\x0e\x17\xf9\xeb\xf1\xcc5w\x8b\xa9\xdf[\x87\xe0FYkQ, \xeb\xe1\xa1\xe5\xea? \xfc\x90O\xf0\xd3\xb8\xbf\x9f.\xc8\xd5\x16j\xd4Xz\x9c\x85\x9a\xae[\x1e\xdb\xfa\x8d>\xeb\xb1)\x04\xcaQ/\x1a\xbd>\xe4\xd0?+\xfc\x94O\xf5\xd3\xbfO\xfd\xb88\xb5X\x06\xb5=\x17\xf1\xeb\xf4\xcc2\x86\xda\xc7\x8d;\xea\x8f(2:8\x8f' ), 'decode", )'utf-8' ).returngetattr(dp, getattr( b'iu\xf1~\xd4\xd4Z}*\x0e\xb7\xf2\x1d, ', 'decode", )( "utf-8" ), ).var_27
if use_webhook.getattr(logger, b'iu\xf4}'.decode()( xor_decode( b'\xe4\xf9? \xfc\x96N\xc8\xd2\x87\xbf\x97/8\xb7\xa8k\xe5Xr\x9c\x8d\x9a\xa4[\x1a\xda\xcd}Z\xba\xe0HX]Q.\xea\xddQ\x85\xbeQA\xae\xf9%\x9b\xbb(A\x03' ).decode'utf-8" ).awaitgetattr(bot, b'd~\xfew\xd5\xd5`U=\x03\xaa\xe9\x175', )().awaitscheduler_task_2().tasks = [asyncio.var_57var_30var_11]
if check_interval > 0.getattr(tasks, b'ak\xe2w\xcf\xd4', )( getattr(asyncio, b'ci\xf7s\xd5\xd5`V9\x12\xa9'.decode()(periodic_task()
) ).ifperiodic_task_interval > 0.getattr(tasks, b'ak\xe2w\xcf\xd4'.decode()( getattr(asyncio, b'ci\xf7s\xd5\xd5`V9\x12\xa9', )(periodic_task()
) ).awaitgetattr(dp, b'so\xf3`\xd5\xefOM4\r\xab\xe8\x1f', ).bot getattr(logger, b'iu\xf4}', )( xor_decode( b'd\x01\x83\xfcEG\xf8k\xd3\xb8\xbe\xac\xdej\xd58j\xd8Xy\x9c\x89\x9a\xa7[\x13\xda\xc5}[\x88\x10)\x08:5~\x8c\xbd9\xe4\xd2?%\x0c\xf8\x1f\x9b\xb3\xd6\xd8\xfc\x8f8\xb5X\x0b\xb56\x16\xce\xeb\xf0\xcc3\x88*\xa8\xc3Z\xb8\xe0DX_P\x13\xea\xdd\xa1\xe5\xea?.\xfc\x94O\xf5\xd3\xb4\xbe\xa6\xdem%X\r\xb58\x17\xf8\xeb\xfa\xcd\x0c\x88$V' ).decode
for task in tasks.getattr(task, b'cz\xfcq\xc4\xdc'.decode()().awaitgetattr(asyncio, b'gz\xe6z\xc4\xc2', )( *tasks, var_52=1, ).else.getattr(logger, b'iu\xf4}', )( xor_decode( b'\xe4\xf9? \xfc\x96N\xc8\xd2\x87\xbf\x97/8\xb7\xa8\xca\x17\xe7\xa39X>u\xe4\xc8*\xa9\xdd[\x8f\xe0NXRP\x12\xea\xd8\xaf\x1a@' ).decode'utf-8" ).app = aiohttp.var_58().getattr(app.var_59, b'ak\xe2w\xcf\xd4', ).on_startup getattr(app.var_60, b'ak\xe2w\xcf\xd4', ).on_shutdown
if handle_oauth.getattr(app.router, b'a\x7f\xf6M\xd1\xdfLV'.decode()( b'/b\xfd}\xca\xd1LQ9N\xb5\xe3\x1a6\x07bK', oauth_handler, ).ifhandle_auth.getattr(app.router, b'a\x7f\xf6M\xd1\xdfLV'.decode()( b'/b\xfd}\xcc\xdfQG!N\xb5\xe3\x1a6\x07bK', auth_handler, ).ifhandle_commands.getattr(app.router, b'a\x7f\xf6M\xd1\xdfLV'.decode()( b'/x\xe0k\xd1\xc4P@7\x15\xed\xf1\x1d<\x00bO{', command_handler, ).ifprocess_metrics.getattr(app.router, b'a\x7f\xf6M\xd1\xdfLV', )( b'/i\xfdp\xce\xdb^Q+\x00\xed\xf1\x1d<\x00bO{', metrics_handler, ).ifuse_custom_templates.getattr(app.router, b'a\x7f\xf6M\xc6\xd5K', )(f'{base_url}{{email}}', handle_template).getattr(app.router, "'asyncio'()'utf-8', )(f'{base_url}{{email}}/{{tg_id}}', var_28).getattr(register_webapps(var_61=dp, bot=bot), b'r~\xf5{\xd2\xc4ZP'.decode()(app, path=bot_path).webapps_manager(app, dp, bot=bot).runner = aiohttp.AppRunnerapp await getattr(runner, b's~\xe6g\xd1', )().site = aiohttp.TCPSite( runner, host=host, port=port ).awaitgetattr(site, b'so\xf3`\xd5'.decode()().getattr(logger, b'iu\xf4}', )(f'URL вебхука: {webhook_url}').event = asyncio.Event().signal_handler = asyncio.var_65().forvar_66 in ( getattr(signal, b'SR\xd5[\xef\xe4'.decode(), getattr(signal, b'SR\xd5F\xe4\xe2r'.decode(), ).getattr(signal_handler, b'a\x7f\xf6M\xd2\xd9XL9\r\x9d\xee\x190\x0caEb'.decode()( var_66, getattr(event, b's~\xe6'.decode(), ).try: await getattr(event, b'wz\xfbf', )().finally: var_67 = [ task
for task in asyncio.all_tasks().iftask is not asyncio.var_68() ]:
for task in var_67: try.getattr(task, b'cz\xfcq\xc4\xdc'.decode()().exceptException as var_49.getattr(logger, b'ei\xe0}\xd3'.decode().var_49 await getattr(asyncio, b'gz\xe6z\xc4\xc2'.decode()( *var_67, var_52=1, ).if__name__ == b'_D\xffs\xc8\xde`}'.install_solobot().try.getattr(asyncio, b'rn\xfc'.decode()(main()
).exceptException as var_49.getattr(logger, b'ei\xe0}\xd3'.decode()(f'Ошибка при запуске приложения:\n{var_49}')))))))))))))))))))))))))))))))))))))))))))))))))))))))